# Generated by Django 5.0.4 on 2024-05-17 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cloth_type',
        ),
        migrations.AddField(
            model_name='order',
            name='special_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.specialtype'),
            preserve_default=False,
        ),
    ]
