# Generated by Django 5.0.4 on 2024-05-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_order_cloth_type_order_special_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complexity',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='worker_amount',
            field=models.CharField(max_length=100),
        ),
    ]
