# Generated by Django 5.0.4 on 2024-05-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_complexity_alter_order_worker_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
